answer_paths:
  cases/eval_0-0-0.yaml:
  - eval_0-0-0_0.txt
  cases/eval_0-0-1.yaml:
  - eval_0-0-1_0.txt
  cases/eval_0-0-10.yaml:
  - eval_0-0-10_0.txt
  cases/eval_0-0-12.yaml:
  - eval_0-0-12_0.txt
  cases/eval_0-0-13.yaml:
  - eval_0-0-13_0.txt
  cases/eval_0-0-14.yaml:
  - eval_0-0-14_0.txt
  cases/eval_0-0-15.yaml:
  - eval_0-0-15_0.txt
  cases/eval_0-0-17.yaml:
  - eval_0-0-17_0.txt
  cases/eval_0-0-19.yaml:
  - eval_0-0-19_0.txt
  cases/eval_0-0-20.yaml:
  - eval_0-0-20_0.txt
  cases/eval_0-0-21.yaml:
  - eval_0-0-21_0.txt
  cases/eval_0-0-22.yaml:
  - eval_0-0-22_0.txt
  cases/eval_0-0-24.yaml:
  - eval_0-0-24_0.txt
  cases/eval_0-0-26.yaml:
  - eval_0-0-26_0.txt
  cases/eval_0-0-27.yaml:
  - eval_0-0-27_0.txt
  cases/eval_0-0-29.yaml:
  - eval_0-0-29_0.txt
  cases/eval_0-0-30.yaml:
  - eval_0-0-30_0.txt
  cases/eval_0-0-31.yaml:
  - eval_0-0-31_0.txt
  cases/eval_0-0-32.yaml:
  - eval_0-0-32_0.txt
  cases/eval_0-0-35.yaml:
  - eval_0-0-35_0.txt
  cases/eval_0-0-36.yaml:
  - eval_0-0-36_0.txt
  cases/eval_0-0-37.yaml:
  - eval_0-0-37_0.txt
  cases/eval_0-0-38.yaml:
  - eval_0-0-38_0.txt
  cases/eval_0-0-39.yaml:
  - eval_0-0-39_0.txt
  cases/eval_0-0-4.yaml:
  - eval_0-0-4_0.txt
  cases/eval_0-0-40.yaml:
  - eval_0-0-40_0.txt
  cases/eval_0-0-41.yaml:
  - eval_0-0-41_0.txt
  cases/eval_0-0-42.yaml:
  - eval_0-0-42_0.txt
  cases/eval_0-0-44.yaml:
  - eval_0-0-44_0.txt
  cases/eval_0-0-46.yaml:
  - eval_0-0-46_0.txt
  cases/eval_0-0-47.yaml:
  - eval_0-0-47_0.txt
  cases/eval_0-0-48.yaml:
  - eval_0-0-48_0.txt
  cases/eval_0-0-5.yaml:
  - eval_0-0-5_0.txt
  cases/eval_0-0-52.yaml:
  - eval_0-0-52_0.txt
  cases/eval_0-0-53.yaml:
  - eval_0-0-53_0.txt
  cases/eval_0-0-54.yaml:
  - eval_0-0-54_0.txt
  cases/eval_0-0-56.yaml:
  - eval_0-0-56_0.txt
  cases/eval_0-0-58.yaml:
  - eval_0-0-58_0.txt
  cases/eval_0-0-59.yaml:
  - eval_0-0-59_0.txt
  cases/eval_0-0-60.yaml:
  - eval_0-0-60_0.txt
  cases/eval_0-0-61.yaml:
  - eval_0-0-61_0.txt
  cases/eval_0-0-62.yaml:
  - eval_0-0-62_0.txt
  cases/eval_0-0-8.yaml:
  - eval_0-0-8_0.txt
  cases/eval_0-0-9.yaml:
  - eval_0-0-9_0.txt
  cases/eval_0-1-134.yaml:
  - eval_0-1-134_0.txt
  cases/eval_0-1-135.yaml:
  - eval_0-1-135_0.txt
  cases/eval_0-1-137.yaml:
  - eval_0-1-137_0.txt
  cases/eval_0-1-138.yaml:
  - eval_0-1-138_0.txt
  cases/eval_0-1-140.yaml:
  - eval_0-1-140_0.txt
  cases/eval_0-1-143.yaml:
  - eval_0-1-143_0.txt
  cases/eval_0-1-144.yaml:
  - eval_0-1-144_0.txt
  cases/eval_0-1-145.yaml:
  - eval_0-1-145_0.txt
  cases/eval_0-1-148.yaml:
  - eval_0-1-148_0.txt
  cases/eval_0-1-149.yaml:
  - eval_0-1-149_0.txt
  cases/eval_0-2-152.yaml:
  - eval_0-2-152_0.txt
  cases/eval_0-2-153.yaml:
  - eval_0-2-153_0.txt
  cases/eval_0-2-154.yaml:
  - eval_0-2-154_0.txt
  cases/eval_0-2-156.yaml:
  - eval_0-2-156_0.txt
  cases/eval_0-2-160.yaml:
  - eval_0-2-160_0.txt
  cases/eval_0-2-162.yaml:
  - eval_0-2-162_0.txt
  cases/eval_0-2-163.yaml:
  - eval_0-2-163_0.txt
  cases/eval_0-2-164.yaml:
  - eval_0-2-164_0.txt
  cases/eval_0-2-166.yaml:
  - eval_0-2-166_0.txt
  cases/eval_0-2-168.yaml:
  - eval_0-2-168_0.txt
max_tokens: null
model_name: gpt-4
qa_system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format. You are chatting with programmers, so please
  answer as briefly as possible.
sample_n: 3
system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format.
temp: 0.2
top_p: 0.9
