answer_paths:
  cases/eval_1-3-173.yaml:
  - eval_1-3-173_0.txt
  - eval_1-3-173_1.txt
  - eval_1-3-173_2.txt
  - eval_1-3-173_3.txt
  - eval_1-3-173_4.txt
  - eval_1-3-173_5.txt
  - eval_1-3-173_6.txt
  - eval_1-3-173_7.txt
  - eval_1-3-173_8.txt
  - eval_1-3-173_9.txt
  cases/eval_1-3-174.yaml:
  - eval_1-3-174_0.txt
  - eval_1-3-174_1.txt
  - eval_1-3-174_2.txt
  - eval_1-3-174_3.txt
  - eval_1-3-174_4.txt
  - eval_1-3-174_5.txt
  - eval_1-3-174_6.txt
  - eval_1-3-174_7.txt
  - eval_1-3-174_8.txt
  - eval_1-3-174_9.txt
  cases/eval_1-3-176.yaml:
  - eval_1-3-176_0.txt
  - eval_1-3-176_1.txt
  - eval_1-3-176_2.txt
  - eval_1-3-176_3.txt
  - eval_1-3-176_4.txt
  - eval_1-3-176_5.txt
  - eval_1-3-176_6.txt
  - eval_1-3-176_7.txt
  - eval_1-3-176_8.txt
  - eval_1-3-176_9.txt
  cases/eval_1-3-180.yaml:
  - eval_1-3-180_0.txt
  - eval_1-3-180_1.txt
  - eval_1-3-180_2.txt
  - eval_1-3-180_3.txt
  - eval_1-3-180_4.txt
  - eval_1-3-180_5.txt
  - eval_1-3-180_6.txt
  - eval_1-3-180_7.txt
  - eval_1-3-180_8.txt
  - eval_1-3-180_9.txt
  cases/eval_1-3-181.yaml:
  - eval_1-3-181_0.txt
  - eval_1-3-181_1.txt
  - eval_1-3-181_2.txt
  - eval_1-3-181_3.txt
  - eval_1-3-181_4.txt
  - eval_1-3-181_5.txt
  - eval_1-3-181_6.txt
  - eval_1-3-181_7.txt
  - eval_1-3-181_8.txt
  - eval_1-3-181_9.txt
  cases/eval_1-3-184.yaml:
  - eval_1-3-184_0.txt
  - eval_1-3-184_1.txt
  - eval_1-3-184_2.txt
  - eval_1-3-184_3.txt
  - eval_1-3-184_4.txt
  - eval_1-3-184_5.txt
  - eval_1-3-184_6.txt
  - eval_1-3-184_7.txt
  - eval_1-3-184_8.txt
  - eval_1-3-184_9.txt
  cases/eval_1-3-187.yaml:
  - eval_1-3-187_0.txt
  - eval_1-3-187_1.txt
  - eval_1-3-187_2.txt
  - eval_1-3-187_3.txt
  - eval_1-3-187_4.txt
  - eval_1-3-187_5.txt
  - eval_1-3-187_6.txt
  - eval_1-3-187_7.txt
  - eval_1-3-187_8.txt
  - eval_1-3-187_9.txt
  cases/eval_1-3-188.yaml:
  - eval_1-3-188_0.txt
  - eval_1-3-188_1.txt
  - eval_1-3-188_2.txt
  - eval_1-3-188_3.txt
  - eval_1-3-188_4.txt
  - eval_1-3-188_5.txt
  - eval_1-3-188_6.txt
  - eval_1-3-188_7.txt
  - eval_1-3-188_8.txt
  - eval_1-3-188_9.txt
  cases/eval_1-3-192.yaml:
  - eval_1-3-192_0.txt
  - eval_1-3-192_1.txt
  - eval_1-3-192_2.txt
  - eval_1-3-192_3.txt
  - eval_1-3-192_4.txt
  - eval_1-3-192_5.txt
  - eval_1-3-192_6.txt
  - eval_1-3-192_7.txt
  - eval_1-3-192_8.txt
  - eval_1-3-192_9.txt
  cases/eval_1-3-193.yaml:
  - eval_1-3-193_0.txt
  - eval_1-3-193_1.txt
  - eval_1-3-193_2.txt
  - eval_1-3-193_3.txt
  - eval_1-3-193_4.txt
  - eval_1-3-193_5.txt
  - eval_1-3-193_6.txt
  - eval_1-3-193_7.txt
  - eval_1-3-193_8.txt
  - eval_1-3-193_9.txt
  cases/eval_1-3-194.yaml:
  - eval_1-3-194_0.txt
  - eval_1-3-194_1.txt
  - eval_1-3-194_2.txt
  - eval_1-3-194_3.txt
  - eval_1-3-194_4.txt
  - eval_1-3-194_5.txt
  - eval_1-3-194_6.txt
  - eval_1-3-194_7.txt
  - eval_1-3-194_8.txt
  - eval_1-3-194_9.txt
  cases/eval_1-3-196.yaml:
  - eval_1-3-196_0.txt
  - eval_1-3-196_1.txt
  - eval_1-3-196_2.txt
  - eval_1-3-196_3.txt
  - eval_1-3-196_4.txt
  - eval_1-3-196_5.txt
  - eval_1-3-196_6.txt
  - eval_1-3-196_7.txt
  - eval_1-3-196_8.txt
  - eval_1-3-196_9.txt
  cases/eval_1-3-197.yaml:
  - eval_1-3-197_0.txt
  - eval_1-3-197_1.txt
  - eval_1-3-197_2.txt
  - eval_1-3-197_3.txt
  - eval_1-3-197_4.txt
  - eval_1-3-197_5.txt
  - eval_1-3-197_6.txt
  - eval_1-3-197_7.txt
  - eval_1-3-197_8.txt
  - eval_1-3-197_9.txt
  cases/eval_1-3-198.yaml:
  - eval_1-3-198_0.txt
  - eval_1-3-198_1.txt
  - eval_1-3-198_2.txt
  - eval_1-3-198_3.txt
  - eval_1-3-198_4.txt
  - eval_1-3-198_5.txt
  - eval_1-3-198_6.txt
  - eval_1-3-198_7.txt
  - eval_1-3-198_8.txt
  - eval_1-3-198_9.txt
  cases/eval_1-3-201.yaml:
  - eval_1-3-201_0.txt
  - eval_1-3-201_1.txt
  - eval_1-3-201_2.txt
  - eval_1-3-201_3.txt
  - eval_1-3-201_4.txt
  - eval_1-3-201_5.txt
  - eval_1-3-201_6.txt
  - eval_1-3-201_7.txt
  - eval_1-3-201_8.txt
  - eval_1-3-201_9.txt
  cases/eval_1-3-202.yaml:
  - eval_1-3-202_0.txt
  - eval_1-3-202_1.txt
  - eval_1-3-202_2.txt
  - eval_1-3-202_3.txt
  - eval_1-3-202_4.txt
  - eval_1-3-202_5.txt
  - eval_1-3-202_6.txt
  - eval_1-3-202_7.txt
  - eval_1-3-202_8.txt
  - eval_1-3-202_9.txt
  cases/eval_1-3-204.yaml:
  - eval_1-3-204_0.txt
  - eval_1-3-204_1.txt
  - eval_1-3-204_2.txt
  - eval_1-3-204_3.txt
  - eval_1-3-204_4.txt
  - eval_1-3-204_5.txt
  - eval_1-3-204_6.txt
  - eval_1-3-204_7.txt
  - eval_1-3-204_8.txt
  - eval_1-3-204_9.txt
  cases/eval_1-3-207.yaml:
  - eval_1-3-207_0.txt
  - eval_1-3-207_1.txt
  - eval_1-3-207_2.txt
  - eval_1-3-207_3.txt
  - eval_1-3-207_4.txt
  - eval_1-3-207_5.txt
  - eval_1-3-207_6.txt
  - eval_1-3-207_7.txt
  - eval_1-3-207_8.txt
  - eval_1-3-207_9.txt
  cases/eval_1-3-208.yaml:
  - eval_1-3-208_0.txt
  - eval_1-3-208_1.txt
  - eval_1-3-208_2.txt
  - eval_1-3-208_3.txt
  - eval_1-3-208_4.txt
  - eval_1-3-208_5.txt
  - eval_1-3-208_6.txt
  - eval_1-3-208_7.txt
  - eval_1-3-208_8.txt
  - eval_1-3-208_9.txt
  cases/eval_1-3-210.yaml:
  - eval_1-3-210_0.txt
  - eval_1-3-210_1.txt
  - eval_1-3-210_2.txt
  - eval_1-3-210_3.txt
  - eval_1-3-210_4.txt
  - eval_1-3-210_5.txt
  - eval_1-3-210_6.txt
  - eval_1-3-210_7.txt
  - eval_1-3-210_8.txt
  - eval_1-3-210_9.txt
  cases/eval_1-3-211.yaml:
  - eval_1-3-211_0.txt
  - eval_1-3-211_1.txt
  - eval_1-3-211_2.txt
  - eval_1-3-211_3.txt
  - eval_1-3-211_4.txt
  - eval_1-3-211_5.txt
  - eval_1-3-211_6.txt
  - eval_1-3-211_7.txt
  - eval_1-3-211_8.txt
  - eval_1-3-211_9.txt
  cases/eval_1-3-212.yaml:
  - eval_1-3-212_0.txt
  - eval_1-3-212_1.txt
  - eval_1-3-212_2.txt
  - eval_1-3-212_3.txt
  - eval_1-3-212_4.txt
  - eval_1-3-212_5.txt
  - eval_1-3-212_6.txt
  - eval_1-3-212_7.txt
  - eval_1-3-212_8.txt
  - eval_1-3-212_9.txt
  cases/eval_1-3-213.yaml:
  - eval_1-3-213_0.txt
  - eval_1-3-213_1.txt
  - eval_1-3-213_2.txt
  - eval_1-3-213_3.txt
  - eval_1-3-213_4.txt
  - eval_1-3-213_5.txt
  - eval_1-3-213_6.txt
  - eval_1-3-213_7.txt
  - eval_1-3-213_8.txt
  - eval_1-3-213_9.txt
  cases/eval_1-3-214.yaml:
  - eval_1-3-214_0.txt
  - eval_1-3-214_1.txt
  - eval_1-3-214_2.txt
  - eval_1-3-214_3.txt
  - eval_1-3-214_4.txt
  - eval_1-3-214_5.txt
  - eval_1-3-214_6.txt
  - eval_1-3-214_7.txt
  - eval_1-3-214_8.txt
  - eval_1-3-214_9.txt
  cases/eval_1-3-217.yaml:
  - eval_1-3-217_0.txt
  - eval_1-3-217_1.txt
  - eval_1-3-217_2.txt
  - eval_1-3-217_3.txt
  - eval_1-3-217_4.txt
  - eval_1-3-217_5.txt
  - eval_1-3-217_6.txt
  - eval_1-3-217_7.txt
  - eval_1-3-217_8.txt
  - eval_1-3-217_9.txt
  cases/eval_1-3-218.yaml:
  - eval_1-3-218_0.txt
  - eval_1-3-218_1.txt
  - eval_1-3-218_2.txt
  - eval_1-3-218_3.txt
  - eval_1-3-218_4.txt
  - eval_1-3-218_5.txt
  - eval_1-3-218_6.txt
  - eval_1-3-218_7.txt
  - eval_1-3-218_8.txt
  - eval_1-3-218_9.txt
  cases/eval_1-3-219.yaml:
  - eval_1-3-219_0.txt
  - eval_1-3-219_1.txt
  - eval_1-3-219_2.txt
  - eval_1-3-219_3.txt
  - eval_1-3-219_4.txt
  - eval_1-3-219_5.txt
  - eval_1-3-219_6.txt
  - eval_1-3-219_7.txt
  - eval_1-3-219_8.txt
  - eval_1-3-219_9.txt
  cases/eval_1-3-222.yaml:
  - eval_1-3-222_0.txt
  - eval_1-3-222_1.txt
  - eval_1-3-222_2.txt
  - eval_1-3-222_3.txt
  - eval_1-3-222_4.txt
  - eval_1-3-222_5.txt
  - eval_1-3-222_6.txt
  - eval_1-3-222_7.txt
  - eval_1-3-222_8.txt
  - eval_1-3-222_9.txt
  cases/eval_1-3-223.yaml:
  - eval_1-3-223_0.txt
  - eval_1-3-223_1.txt
  - eval_1-3-223_2.txt
  - eval_1-3-223_3.txt
  - eval_1-3-223_4.txt
  - eval_1-3-223_5.txt
  - eval_1-3-223_6.txt
  - eval_1-3-223_7.txt
  - eval_1-3-223_8.txt
  - eval_1-3-223_9.txt
  cases/eval_1-3-224.yaml:
  - eval_1-3-224_0.txt
  - eval_1-3-224_1.txt
  - eval_1-3-224_2.txt
  - eval_1-3-224_3.txt
  - eval_1-3-224_4.txt
  - eval_1-3-224_5.txt
  - eval_1-3-224_6.txt
  - eval_1-3-224_7.txt
  - eval_1-3-224_8.txt
  - eval_1-3-224_9.txt
  cases/eval_1-3-225.yaml:
  - eval_1-3-225_0.txt
  - eval_1-3-225_1.txt
  - eval_1-3-225_2.txt
  - eval_1-3-225_3.txt
  - eval_1-3-225_4.txt
  - eval_1-3-225_5.txt
  - eval_1-3-225_6.txt
  - eval_1-3-225_7.txt
  - eval_1-3-225_8.txt
  - eval_1-3-225_9.txt
  cases/eval_1-3-226.yaml:
  - eval_1-3-226_0.txt
  - eval_1-3-226_1.txt
  - eval_1-3-226_2.txt
  - eval_1-3-226_3.txt
  - eval_1-3-226_4.txt
  - eval_1-3-226_5.txt
  - eval_1-3-226_6.txt
  - eval_1-3-226_7.txt
  - eval_1-3-226_8.txt
  - eval_1-3-226_9.txt
  cases/eval_1-3-230.yaml:
  - eval_1-3-230_0.txt
  - eval_1-3-230_1.txt
  - eval_1-3-230_2.txt
  - eval_1-3-230_3.txt
  - eval_1-3-230_4.txt
  - eval_1-3-230_5.txt
  - eval_1-3-230_6.txt
  - eval_1-3-230_7.txt
  - eval_1-3-230_8.txt
  - eval_1-3-230_9.txt
  cases/eval_1-3-231.yaml:
  - eval_1-3-231_0.txt
  - eval_1-3-231_1.txt
  - eval_1-3-231_2.txt
  - eval_1-3-231_3.txt
  - eval_1-3-231_4.txt
  - eval_1-3-231_5.txt
  - eval_1-3-231_6.txt
  - eval_1-3-231_7.txt
  - eval_1-3-231_8.txt
  - eval_1-3-231_9.txt
  cases/eval_1-3-235.yaml:
  - eval_1-3-235_0.txt
  - eval_1-3-235_1.txt
  - eval_1-3-235_2.txt
  - eval_1-3-235_3.txt
  - eval_1-3-235_4.txt
  - eval_1-3-235_5.txt
  - eval_1-3-235_6.txt
  - eval_1-3-235_7.txt
  - eval_1-3-235_8.txt
  - eval_1-3-235_9.txt
  cases/eval_1-3-236.yaml:
  - eval_1-3-236_0.txt
  - eval_1-3-236_1.txt
  - eval_1-3-236_2.txt
  - eval_1-3-236_3.txt
  - eval_1-3-236_4.txt
  - eval_1-3-236_5.txt
  - eval_1-3-236_6.txt
  - eval_1-3-236_7.txt
  - eval_1-3-236_8.txt
  - eval_1-3-236_9.txt
  cases/eval_1-3-239.yaml:
  - eval_1-3-239_0.txt
  - eval_1-3-239_1.txt
  - eval_1-3-239_2.txt
  - eval_1-3-239_3.txt
  - eval_1-3-239_4.txt
  - eval_1-3-239_5.txt
  - eval_1-3-239_6.txt
  - eval_1-3-239_7.txt
  - eval_1-3-239_8.txt
  - eval_1-3-239_9.txt
  cases/eval_1-3-240.yaml:
  - eval_1-3-240_0.txt
  - eval_1-3-240_1.txt
  - eval_1-3-240_2.txt
  - eval_1-3-240_3.txt
  - eval_1-3-240_4.txt
  - eval_1-3-240_5.txt
  - eval_1-3-240_6.txt
  - eval_1-3-240_7.txt
  - eval_1-3-240_8.txt
  - eval_1-3-240_9.txt
  cases/eval_1-3-242.yaml:
  - eval_1-3-242_0.txt
  - eval_1-3-242_1.txt
  - eval_1-3-242_2.txt
  - eval_1-3-242_3.txt
  - eval_1-3-242_4.txt
  - eval_1-3-242_5.txt
  - eval_1-3-242_6.txt
  - eval_1-3-242_7.txt
  - eval_1-3-242_8.txt
  - eval_1-3-242_9.txt
  cases/eval_1-3-244.yaml:
  - eval_1-3-244_0.txt
  - eval_1-3-244_1.txt
  - eval_1-3-244_2.txt
  - eval_1-3-244_3.txt
  - eval_1-3-244_4.txt
  - eval_1-3-244_5.txt
  - eval_1-3-244_6.txt
  - eval_1-3-244_7.txt
  - eval_1-3-244_8.txt
  - eval_1-3-244_9.txt
  cases/eval_1-3-245.yaml:
  - eval_1-3-245_0.txt
  - eval_1-3-245_1.txt
  - eval_1-3-245_2.txt
  - eval_1-3-245_3.txt
  - eval_1-3-245_4.txt
  - eval_1-3-245_5.txt
  - eval_1-3-245_6.txt
  - eval_1-3-245_7.txt
  - eval_1-3-245_8.txt
  - eval_1-3-245_9.txt
  cases/eval_1-3-247.yaml:
  - eval_1-3-247_0.txt
  - eval_1-3-247_1.txt
  - eval_1-3-247_2.txt
  - eval_1-3-247_3.txt
  - eval_1-3-247_4.txt
  - eval_1-3-247_5.txt
  - eval_1-3-247_6.txt
  - eval_1-3-247_7.txt
  - eval_1-3-247_8.txt
  - eval_1-3-247_9.txt
  cases/eval_1-3-249.yaml:
  - eval_1-3-249_0.txt
  - eval_1-3-249_1.txt
  - eval_1-3-249_2.txt
  - eval_1-3-249_3.txt
  - eval_1-3-249_4.txt
  - eval_1-3-249_5.txt
  - eval_1-3-249_6.txt
  - eval_1-3-249_7.txt
  - eval_1-3-249_8.txt
  - eval_1-3-249_9.txt
  cases/eval_1-3-252.yaml:
  - eval_1-3-252_0.txt
  - eval_1-3-252_1.txt
  - eval_1-3-252_2.txt
  - eval_1-3-252_3.txt
  - eval_1-3-252_4.txt
  - eval_1-3-252_5.txt
  - eval_1-3-252_6.txt
  - eval_1-3-252_7.txt
  - eval_1-3-252_8.txt
  - eval_1-3-252_9.txt
  cases/eval_1-3-257.yaml:
  - eval_1-3-257_0.txt
  - eval_1-3-257_1.txt
  - eval_1-3-257_2.txt
  - eval_1-3-257_3.txt
  - eval_1-3-257_4.txt
  - eval_1-3-257_5.txt
  - eval_1-3-257_6.txt
  - eval_1-3-257_7.txt
  - eval_1-3-257_8.txt
  - eval_1-3-257_9.txt
  cases/eval_1-3-261.yaml:
  - eval_1-3-261_0.txt
  - eval_1-3-261_1.txt
  - eval_1-3-261_2.txt
  - eval_1-3-261_3.txt
  - eval_1-3-261_4.txt
  - eval_1-3-261_5.txt
  - eval_1-3-261_6.txt
  - eval_1-3-261_7.txt
  - eval_1-3-261_8.txt
  - eval_1-3-261_9.txt
  cases/eval_1-3-263.yaml:
  - eval_1-3-263_0.txt
  - eval_1-3-263_1.txt
  - eval_1-3-263_2.txt
  - eval_1-3-263_3.txt
  - eval_1-3-263_4.txt
  - eval_1-3-263_5.txt
  - eval_1-3-263_6.txt
  - eval_1-3-263_7.txt
  - eval_1-3-263_8.txt
  - eval_1-3-263_9.txt
  cases/eval_1-4-315.yaml:
  - eval_1-4-315_0.txt
  - eval_1-4-315_1.txt
  - eval_1-4-315_2.txt
  - eval_1-4-315_3.txt
  - eval_1-4-315_4.txt
  - eval_1-4-315_5.txt
  - eval_1-4-315_6.txt
  - eval_1-4-315_7.txt
  - eval_1-4-315_8.txt
  - eval_1-4-315_9.txt
  cases/eval_1-4-316.yaml:
  - eval_1-4-316_0.txt
  - eval_1-4-316_1.txt
  - eval_1-4-316_2.txt
  - eval_1-4-316_3.txt
  - eval_1-4-316_4.txt
  - eval_1-4-316_5.txt
  - eval_1-4-316_6.txt
  - eval_1-4-316_7.txt
  - eval_1-4-316_8.txt
  - eval_1-4-316_9.txt
  cases/eval_1-4-317.yaml:
  - eval_1-4-317_0.txt
  - eval_1-4-317_1.txt
  - eval_1-4-317_2.txt
  - eval_1-4-317_3.txt
  - eval_1-4-317_4.txt
  - eval_1-4-317_5.txt
  - eval_1-4-317_6.txt
  - eval_1-4-317_7.txt
  - eval_1-4-317_8.txt
  - eval_1-4-317_9.txt
  cases/eval_1-4-320.yaml:
  - eval_1-4-320_0.txt
  - eval_1-4-320_1.txt
  - eval_1-4-320_2.txt
  - eval_1-4-320_3.txt
  - eval_1-4-320_4.txt
  - eval_1-4-320_5.txt
  - eval_1-4-320_6.txt
  - eval_1-4-320_7.txt
  - eval_1-4-320_8.txt
  - eval_1-4-320_9.txt
  cases/eval_1-4-321.yaml:
  - eval_1-4-321_0.txt
  - eval_1-4-321_1.txt
  - eval_1-4-321_2.txt
  - eval_1-4-321_3.txt
  - eval_1-4-321_4.txt
  - eval_1-4-321_5.txt
  - eval_1-4-321_6.txt
  - eval_1-4-321_7.txt
  - eval_1-4-321_8.txt
  - eval_1-4-321_9.txt
  cases/eval_1-4-322.yaml:
  - eval_1-4-322_0.txt
  - eval_1-4-322_1.txt
  - eval_1-4-322_2.txt
  - eval_1-4-322_3.txt
  - eval_1-4-322_4.txt
  - eval_1-4-322_5.txt
  - eval_1-4-322_6.txt
  - eval_1-4-322_7.txt
  - eval_1-4-322_8.txt
  - eval_1-4-322_9.txt
  cases/eval_1-4-323.yaml:
  - eval_1-4-323_0.txt
  - eval_1-4-323_1.txt
  - eval_1-4-323_2.txt
  - eval_1-4-323_3.txt
  - eval_1-4-323_4.txt
  - eval_1-4-323_5.txt
  - eval_1-4-323_6.txt
  - eval_1-4-323_7.txt
  - eval_1-4-323_8.txt
  - eval_1-4-323_9.txt
  cases/eval_1-4-324.yaml:
  - eval_1-4-324_0.txt
  - eval_1-4-324_1.txt
  - eval_1-4-324_2.txt
  - eval_1-4-324_3.txt
  - eval_1-4-324_4.txt
  - eval_1-4-324_5.txt
  - eval_1-4-324_6.txt
  - eval_1-4-324_7.txt
  - eval_1-4-324_8.txt
  - eval_1-4-324_9.txt
  cases/eval_1-4-326.yaml:
  - eval_1-4-326_0.txt
  - eval_1-4-326_1.txt
  - eval_1-4-326_2.txt
  - eval_1-4-326_3.txt
  - eval_1-4-326_4.txt
  - eval_1-4-326_5.txt
  - eval_1-4-326_6.txt
  - eval_1-4-326_7.txt
  - eval_1-4-326_8.txt
  - eval_1-4-326_9.txt
  cases/eval_1-4-327.yaml:
  - eval_1-4-327_0.txt
  - eval_1-4-327_1.txt
  - eval_1-4-327_2.txt
  - eval_1-4-327_3.txt
  - eval_1-4-327_4.txt
  - eval_1-4-327_5.txt
  - eval_1-4-327_6.txt
  - eval_1-4-327_7.txt
  - eval_1-4-327_8.txt
  - eval_1-4-327_9.txt
max_tokens: null
model_name: gpt-4
qa_system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format. You are chatting with programmers, so please
  answer as briefly as possible.
sample_n: 10
system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format.
temp: 0.2
top_p: 0.9
